name: 'JS Setup'
description: "Setup everything for the project"

inputs:
    node-version:
        description: 'Node Version'
        required: false
        default: '20'

runs:
    using: 'composite'
    steps:
        - name: Install NodeJS
          uses: actions/setup-node@v2
          with:
              node-version: ${{ inputs.node-version }}
              cache: 'npm'

        - name: Install dependencies
          run: npm install
          shell: bash