name: 'Testsuite'

on:
    pull_request:

jobs:
    testsuite:
        name: "Run testsuite"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                branch:
                    - ${{ github.head_ref }}
                    - "master"

        permissions:
            # Required to checkout the code
            contents: read
            # Required to put a comment into the pull-request
            pull-requests: write

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
              with:
                  ref: ${{ matrix.branch }}

            - name: JS Setup
              uses: ./.github/actions/js-setup

            - name: Run the check
              run: npm run test:coverage

            - name: Upload coverage
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-${{ matrix.branch }}
                  path: coverage

    report-coverage:
        needs: testsuite
        runs-on: ubuntu-latest
        steps:
            - name: Download Coverage Artifacts
              uses: actions/download-artifact@v4
              with:
                name: coverage-${{ github.head_ref }}
                path: coverage

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: coverage-master
                path: coverage-master

            - name: "Report Coverage"
              uses: davelosert/vitest-coverage-report-action@v2
              with:
                json-summary-compare-path: coverage-master/coverage-summary.json
