name: 'Testsuite'

on:
    pull_request:

jobs:
    testsuite:
        name: "Run testsuite"
        runs-on: ubuntu-latest

        permissions:
            # Required to checkout the code
            contents: read
            # Required to put a comment into the pull-request
            pull-requests: write

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: JS Setup
              uses: ./.github/actions/js-setup

            - name: Run the check
              run: npm run test:coverage

            - name: 'Report Coverage'
              # Set if: always() to also generate the report if tests are failing
              # Only works if you set `reportOnFailure: true` in your vite config as specified above
              if: always()
              uses: davelosert/vitest-coverage-report-action@v2