name: 'Type Check'

on:
    pull_request:

jobs:
    type-check:
        name: "Run type check"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: JS Setup
              uses: ./.github/actions/js-setup

            - name: Run the check
              run: npm run type-check