name: 'Type check'

on:
    pull_request:

jobs:
    type-check:
        name: "Type check"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Run the check
              run: npm run type-check